name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - name: Default
      run: echo 'envs ${{ secrets.CODECOV_TOKEN }}!'
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm run install

    - name: Run tests
      run: npm run test
    - name: locate coverageDirectory
      run: ls /home/runner/work/test/test/coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
