name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - name: Default
      run: echo 'envs ${{ secrets.CODECOV_TOKEN }}!'
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test
    - name: Check coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      with:
        path: './coverage/lcov.info'
        min_coverage: 90    
    
