name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Get Coverage for badge
      run: |
        SUMMARY="$(npm run test:coverage | grep Lines)"
        TOKENS=($SUMMARY)
        # set env variable with value of coverage
        echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV 
        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: test__${{ env.BRANCH }}.json # Filename created in gist
        label: Test Coverage 
        message: ${{ env.COVERAGE }}
        color: orange # Can be calculated using the value of env.COVERAGE
        namedLogo: jest
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: ![Coverage Badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/hsilva35/d028c539a04b9339b27aff7c865e1e1b/raw/test__${{ env.BRANCH }}.json) });