name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - name: Default
      run: echo 'envs ${{ secrets.CODECOV_TOKEN }}!'
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Run lint
      run: npm run lint:report
    - name: locate coverageDirectory
      run: ls /home/runner/work/test/test/coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: eslint_report.json
