name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    
    steps:
    - name: Default
      run: echo 'envs ${{ secrets.CODECOV_TOKEN }}!'
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Run lint
      run: npm run lint:report
    - name: Get Coverage for badge
      run: |
        SUMMARY="$(npm run test:coverage | grep Lines |grep -Eo '[0-9]+\.[0-9]+')"

        echo "COVERAGE=$(echo ${SUMMARY} | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: test__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}%
        color: orange
        namedLogo: jest